import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'fs';
import path from 'path';
import os from 'os';
import { spawn, ChildProcess } from 'child_process';
import { execSync, ExecSyncOptions } from 'child_process';

const cliPath = path.resolve(__dirname, '../../dist/index.cjs');
const wait = (ms: number) => new Promise((r) => setTimeout(r, ms));

function mkTmp(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'coster-daemon-'));
}
function run(tmp: string, args: string, opts: Partial<ExecSyncOptions> = {}): string {
  const full: ExecSyncOptions = { cwd: tmp, encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'], ...opts };
  try {
    return execSync(`node "${cliPath}" ${args}`, full).toString();
  } catch (e: any) {
    return (e.stdout?.toString() ?? '') + '\n' + (e.stderr?.toString() ?? '');
  }
}

describe('daemon file-watch (M1)', () => {
  let tmp: string;
  let child: ChildProcess | null = null;

  beforeEach(() => {
    tmp = mkTmp();
  });
  afterEach(async () => {
    if (child) {
      try {
        child.kill('SIGTERM');
        await new Promise((r) => child!.on('exit', r));
      } catch {
        /* ignore */
      }
      child = null;
    }
    await wait(300);
    fs.rmSync(tmp, { recursive: true, force: true });
  });

  it('auto-discovers and syncs when a new tool marker appears', async () => {
    run(tmp, 'init');
    const pidPath = path.join(tmp, '.coster', 'daemon.pid');

    child = spawn('node', [cliPath, 'daemon', 'start'], { cwd: tmp, stdio: 'ignore' });
    // allow the daemon to boot + write its pidfile
    await wait(900);
    expect(fs.existsSync(pidPath)).toBe(true);

    // Simulate the user adding a Codex workspace later.
    fs.mkdirSync(path.join(tmp, '.codex'), { recursive: true });
    fs.writeFileSync(path.join(tmp, '.codex', 'memory.md'), '');

    // debounce is 1500ms; wait for the sync to run.
    await wait(2800);

    const cfg = JSON.parse(fs.readFileSync(path.join(tmp, '.coster', 'config.json'), 'utf-8'));
    expect(cfg.tools.find((t: any) => t.name === 'codex').enabled).toBe(true);

    // codex memory file generated by the sync
    expect(fs.existsSync(path.join(tmp, '.codex', 'memory.md'))).toBe(true);

    child.kill('SIGTERM');
    await new Promise((r) => child!.on('exit', r));
    child = null;
  }, 30000);
});
